### ISSUE TITLE
can implement pull up and  auto loadmore and multi-fingered

### ISSUE THREAD

**Issue by krmao** [Yalantis/Phoenix#10]
can you implement:
1: pull up ,which show need pull up 
2:load more, which auto show,can click loadmore and pull up load more
3:multi-fingered pull up and down 
thanks !

**Comment by nukc** [comment]
+1

**Comment by devilsen** [comment]
+1

**Comment by shliama** [comment]
Yes I can, but I do not have time to do all of that. But that's why it's open-sourced :) so you all are welcomed to fork / pull-request to extend the lib's features.
