### ISSUE TITLE
Unable to customize sun.png

### ISSUE THREAD

**Issue by gouravd** [Yalantis/Phoenix#11]
When I add a sun.png, I get the error Duplicate file. 
<path>\app\build\intermediates\res\debug\drawable-xxhdpi\sun.png: Original is here. The version qualifier may be implied.

I assume, I would need to set the merger to use my project's sun.png, but not sure how to do it.

**Comment by shliama** [comment]
@gouravd Do you change it inside the library? Have you cleaned project before building it?
