### ISSUE TITLE
Padding disappear after refresh

### ISSUE THREAD

**Issue by qingchengnus** [Yalantis/Phoenix#13]
I set padding top and padding bottom to the list view and the padding disappears after refresh. I want to set clipToPadding of the listview to false, so moving the padding to PullToRefreshView will not work in my case.

**Comment by shliama** [comment]
@qingchengnus yeah, already know about this bug, and in fact already have a fix, but haven't had enough time to implement it.
clipToPadding won't work because it is set to true inside the PullToRefreshView class.

I think, I'll include the fix in the next update during today/tomorrow.

**Comment by shliama** [comment]
@qingchengnus should be fixed in 1.2.1
