### ISSUE TITLE
undetected ViewCompat.setChildrenDrawingOrderEnabled(this, true); method

### ISSUE THREAD

**Issue by sys-samk** [Yalantis/Phoenix#14]
I have an error.
this method undetected.
can you help me?

**Comment by shliama** [comment]
@sys-samk Can you reproduce this error with the sample?
Also be sure you have Support v4 and AppCompat Support Libraries dependencies included in your project's build.gradle.

**Comment by wangzh0617** [comment]
What time does it support RecyclerView?

**Comment by shliama** [comment]
It already does support RecyclerView, please, check out the sample
