### ISSUE TITLE
What's the difference between https://github.com/Yalantis/Taurus and this project?

### ISSUE THREAD

**Issue by huangcd** [Yalantis/Phoenix#15]

**Comment by shliama** [comment]
@huangcd I'm sure the difference is quite visible https://d13yacurqjgara.cloudfront.net/users/125056/screenshots/1650317/realestate-pull_1-2-3.gif
https://d13yacurqjgara.cloudfront.net/users/125056/screenshots/1623131/tours-pull-airplane_2-2-3.gif
