### ISSUE TITLE
While refreshing - it's impossible to scroll list all the way down

### ISSUE THREAD

**Issue by shliama** [Yalantis/Phoenix#2]

**Comment by meierjan** [comment]
+1

**Comment by tosslife** [comment]
+1

**Comment by tosslife** [comment]
@shliama  hi ！ can you fix it ? hope^^

**Comment by shliama** [comment]
Yeah, I'm going to take a look at this bug this week. Not sure when, but till the end of the week I'll post an update here.

**Comment by shliama** [comment]
@tosslife @meierjan  I've found a simple way to achieve desired behaviour, and updated code in master branch.
P.S. I'll be able to update library on maven on Monday.

**Comment by tosslife** [comment]
@shliama  love you ^^ hope monday

**Comment by shliama** [comment]
@tosslife sure (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

**Comment by tosslife** [comment]
@shliama  i run the new project , while refreshing scroll the list, the loading view is float the top, why not make loading view  follow with list scroll ,it may be feel better!

**Comment by shliama** [comment]
@tosslife Yeah, I understand your proposal, and agree with that. This should be changed in next update.
Maybe next weekend I'll have some free time to do that. 
Anyway, I've updated maven repo so you can grab version 1.1.1 from there with latest fix.

**Comment by tosslife** [comment]
@shliama hope next weekend !  it is a good nice ^^

**Comment by shliama** [comment]
I've researched the ways to do this, and it's seems not to be easy. Unfortunately, at the moment I don't have enough time, but soon we may use this library in one of our's project and make this improvement.

**Comment by tosslife** [comment]
@shliama   thanks ! and  https://github.com/Yalantis/FoldingTabBar.iOS   your team's project ,when this can achieve for android ? very hope !

**Comment by shliama** [comment]
@tosslife unfortunately I cannot give you any estimations on that, but for sure - it will be created some day.
