### ISSUE TITLE
when I need load more?

### ISSUE THREAD

**Issue by yangyunfeng666** [Yalantis/Phoenix#21]
when I need load more?,the code how to write?

**Comment by shliama** [comment]
The question is obscure to me, more information you must provide.

**Comment by yangyunfeng666** [comment]
sorry I English is poor,I mean that when I want to load more information from server,because demo only have refresh code not include load more method.you can give me other advices.

**Comment by shliama** [comment]
Oh I see.
But let me be clear - this library has only pull-to-refresh feature at the moment.
What you are looking for is called "Endless Scrolling" (e.g. here is a link on "how-to" do it https://github.com/codepath/android_guides/wiki/Endless-Scrolling-with-AdapterViews).

We'll try to add this feature in future updates :)

**Comment by yangyunfeng666** [comment]
thank you very much.

**Comment by shliama** [comment]
You're welcome!
