### ISSUE TITLE
can I use this library like this?

### ISSUE THREAD

**Issue by zhouhytx2010** [Yalantis/Phoenix#25]
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

```
<com.yalantis.phoenix.PullToRefreshView
    android:id="@+id/pull_to_refresh"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</com.yalantis.phoenix.PullToRefreshView>
```

</RelativeLayout>

If I use the library like this, it can't pull to refresh, how can I do it ?

**Comment by shliama** [comment]
@zhouhytx2010 
You see, library needs some scrollable view to work (ListView, RecyclerView or ScrollView).
For your issue I suggest to wrap your ImageView with just ScrollView.
I've just tested this workaround and it worked :)

**Comment by TeeRawk** [comment]
Outdated
