### ISSUE TITLE
Change sun,circle ,buildings images programatically

### ISSUE THREAD

**Issue by rambabupudari** [Yalantis/Phoenix#29]
Hi Author,
I have added gradle line in my project.How can i change the circle,sun,Building images with my own images problematically.

**Comment by rasystems** [comment]
Hi rambabupudari!
I use the librarie and it seems that there is still a bug . I could not change the Pictures successfully. Author please fix the problem!

**Comment by TeeRawk** [comment]
To change the image in animation , just place your picture in res/drawable  and name it sun.png (for example)

**Comment by Dev-Wiki** [comment]
I place pictures in my app res/drawable,but it not work~
![](http://image.prntscr.com/image/f593782ff2534d55b9ab12bff6766d27.png)

**Comment by TeeRawk** [comment]
Try to place them like this 
![image](https://cloud.githubusercontent.com/assets/13538078/17960478/f6a5e8a6-6aae-11e6-8aa8-63f6986b5d95.png)

**Comment by TeeRawk** [comment]
outdated
