### ISSUE TITLE
Scroll doesn't work with complex layouts

### ISSUE THREAD

**Issue by bradmartin** [Yalantis/Phoenix#34]
This might be fixed with this PR: https://github.com/Yalantis/Phoenix/pull/31

If you watch the .gif below, you'll see that I can scroll this ListView down and up if I continue the touch. Once the touch has been lifted from the screen and you swipe down it starts show the refresh view. Normal behavior should not show this unless at the top of the ListView.

Was this by design?

![phoenixscrollissue](https://cloud.githubusercontent.com/assets/6006148/15767171/933454cc-290b-11e6-84e6-339276c0c0ab.gif)

**Comment by AhmedDonkl** [comment]
@bradmartin  did you solve it ?

**Comment by TeeRawk** [comment]
@bradmartin  can you provide the layout where your PullToRefreshView is ?

**Comment by TeeRawk** [comment]
outdated
