### ISSUE TITLE
Resource name "type" conflicts with other lib

### ISSUE THREAD

**Issue by rostopira** [Yalantis/Phoenix#36]
I'm not sure, which exactly, but I can't even sync gradle with this lib. Debug values contains following code

   ```
 <declare-styleable name="LiveLockScreen"><attr format="string" name="settingsActivity"/><attr name="type">
            <flag name="experience" value="1"/>
            <flag name="event" value="2"/>
        </attr></declare-styleable>
```

**Comment by warko-san** [comment]
Hi, @rostopira! It's weird. What other libraries are you using with this one?

**Comment by rostopira** [comment]
@warko-san I use a lot of libs, but I think problem is in one of the following

- CyanogenMod SDK (most probably)
- Twitter and Digits SDKs from Fabric
- Facebook SDK
- Firebase Invites or Auth

**Comment by PenzK** [comment]
@rostopira what is the gradle message?

**Comment by PenzK** [comment]
If it is the case you can add lib as lib project and change the attribute's name
