### ISSUE TITLE
How can i disable it programatically?

### ISSUE THREAD

**Issue by svetaz** [Yalantis/Phoenix#45]
Hello, is it possible to disable it programatically,because i want it to be active only when specific view is touched and not the rest of the layout?

Thanks in advance :)
Great lib btw !

**Comment by svetaz** [comment]
More details: i have a nested scroll view,and when im swiping down it doesnt scroll up my view,instead it activates Phoenix refresh :) Please help me.

**Comment by svetaz** [comment]
Nvm,found a solution :D Will email you once the app is done,thanks!

**Comment by pinkgom** [comment]
I write down methods for those wondering how to handle like me.
Use API below.
 .setEnable(boolean enabled)
