### ISSUE TITLE
Size of the Background Animation in Master/Detail Pane Layout 

### ISSUE THREAD

**Issue by meierjan** [Yalantis/Phoenix#7]
The thing is that If you are using the Android Studio template for Master/Detail Flow's there is a bug in the sizing of the Background Animation. It seems that your code uses the Device width as the Animation width - but It should use the fragment/activity width instead.

![bildschirmfoto 2015-03-16 um 22 49 52](https://cloud.githubusercontent.com/assets/3726563/6677293/d75abff0-cc2e-11e4-9fd3-efe8adc4b340.png)

I hope you get what I mean.

**Comment by shliama** [comment]
@meierjan thanks for reporting, and huuuugeeee sorry for late answer. 
I'll try to fix this this weekend.

**Comment by shliama** [comment]
Fixed in version 1.1.2

**Comment by meierjan** [comment]
Am I wrong or is there is no such version tag.

**Comment by shliama** [comment]
@meierjan you are wrong

http://mvnrepository.com/artifact/com.yalantis/phoenix/1.1.2
http://gradleplease.appspot.com/#com.yalantis
